const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const multer = require('multer');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const path = require('path');
const fs = require('fs');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const app = express();
const PORT = process.env.PORT || 5000;
const JWT_SECRET = process.env.JWT_SECRET || 'cabiir-development-secret-change-me';
const uploads = path.join(__dirname, 'uploads');
fs.mkdirSync(uploads, { recursive: true });
app.use(cors());
app.use(express.json({ limit: '100kb' }));
app.use('/uploads', express.static(uploads));

const storage = multer.diskStorage({ destination: uploads, filename: (_, file, cb) => cb(null, `profile-${Date.now()}${path.extname(file.originalname).toLowerCase()}`) });
const upload = multer({ storage, limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: (_, file, cb) => cb(null, /^image\/(jpeg|png|webp|gif)$/.test(file.mimetype)) });
const registrationSchema = new mongoose.Schema({ fullName: { type: String, required: true, trim: true, maxlength: 100 }, phone: { type: String, required: true, trim: true, maxlength: 30 }, passportNumber: { type: String, required: true, trim: true, maxlength: 40 }, date: { type: String, required: true }, goDate: { type: String, required: true }, backDate: { type: String, required: true }, hotel: { type: String, trim: true, maxlength: 120 }, places: { type: String, trim: true, maxlength: 500 }, reference: { type: String, default: '—', trim: true, maxlength: 80 }, moneyAmount: { type: Number, default: 0, min: 0 }, paid: { type: Boolean, default: false } }, { timestamps: true });
const deletedSchema = new mongoose.Schema({ originalId: { type: mongoose.Schema.Types.ObjectId, required: true }, recordType: { type: String, enum: ['cumrah', 'hajj', 'visitors', 'user'], required: true }, record: { type: mongoose.Schema.Types.Mixed, required: true }, deletedBy: { id: mongoose.Schema.Types.ObjectId, fullName: String, username: String }, deletedAt: { type: Date, default: Date.now } }, { timestamps: true });
const userSchema = new mongoose.Schema({ fullName: { type: String, required: true, trim: true, maxlength: 100 }, username: { type: String, required: true, unique: true, lowercase: true, trim: true, minlength: 3, maxlength: 40 }, passwordHash: { type: String, required: true }, branch: { type: String, enum: ['hargeisa', 'jidda'], required: true }, profileImage: String, logoImage: String }, { timestamps: true });
const models = { cumrah: mongoose.model('CumrahRegistration', registrationSchema, 'cumrahRegistrations'), hajj: mongoose.model('HajjRegistration', registrationSchema, 'hajjRegistrations'), visitors: mongoose.model('VisitorRegistration', registrationSchema, 'visitorRegistrations') };
const DeletedRecord = mongoose.model('DeletedRecord', deletedSchema, 'deletedRecords');
const User = mongoose.model('User', userSchema, 'users');
const cleanPayload = body => { const allowed = ['fullName', 'phone', 'passportNumber', 'date', 'goDate', 'backDate', 'hotel', 'places', 'reference']; const payload = Object.fromEntries(allowed.filter(key => body[key] !== undefined).map(key => [key, String(body[key]).trim()])); if (body.moneyAmount !== undefined) payload.moneyAmount = Number(body.moneyAmount); if (body.paid !== undefined) payload.paid = Boolean(body.paid); return payload; };
const publicUser = user => ({ id: user._id, fullName: user.fullName, username: user.username, branch: user.branch, profileImage: Boolean(user.profileImage), logoImage: Boolean(user.logoImage), createdAt: user.createdAt });
const publicDeleted = item => { const data = item.toObject ? item.toObject() : item; if (data.recordType === 'user' && data.record) { const { passwordHash, ...safeRecord } = data.record; data.record = safeRecord; } return data; };
const tokenFor = user => jwt.sign({ id: user._id.toString(), branch: user.branch, username: user.username }, JWT_SECRET, { expiresIn: '8h' });
const requireAuth = async (req, res, next) => { try { const header = req.headers.authorization || ''; if (!header.startsWith('Bearer ')) return res.status(401).json({ message: 'Authentication required.' }); const payload = jwt.verify(header.slice(7), JWT_SECRET); const user = await User.findById(payload.id); if (!user) return res.status(401).json({ message: 'Session is no longer valid.' }); req.user = user; next(); } catch { res.status(401).json({ message: 'Authentication required.' }); } };
const requireBranch = branch => (req, res, next) => { if (req.user.branch !== branch) return res.status(403).json({ message: `This account cannot access the ${branch} dashboard.` }); next(); };

app.post('/api/auth/login', async (req, res, next) => { try { const username = String(req.body.username || '').trim().toLowerCase(); const password = String(req.body.password || ''); const user = await User.findOne({ username }); if (!user || !(await bcrypt.compare(password, user.passwordHash))) return res.status(401).json({ message: 'Username or password is incorrect.' }); res.json({ token: tokenFor(user), user: publicUser(user) }); } catch (error) { next(error); } });
app.post('/api/auth/register', requireAuth, requireBranch('hargeisa'), async (req, res, next) => { try { const { fullName, username, password, confirmPassword, branch } = req.body; if (!fullName || !username || !password || password !== confirmPassword || branch !== 'jidda') return res.status(400).json({ message: 'Complete all fields and select the Jidda branch.' }); const passwordHash = await bcrypt.hash(password, 12); const user = await User.create({ fullName: String(fullName).trim(), username: String(username).trim().toLowerCase(), passwordHash, branch }); res.status(201).json({ user: publicUser(user), message: 'Account created. You can now log in.' }); } catch (error) { error.status = error.code === 11000 ? 409 : 400; error.message = error.code === 11000 ? 'That username is already in use.' : error.message; next(error); } });
app.get('/api/auth/me', requireAuth, (req, res) => res.json({ user: publicUser(req.user) }));
app.post('/api/auth/logout', requireAuth, (_, res) => res.status(204).end());

const addRegistrationRoutes = type => { const Model = models[type];
  app.post(`/api/${type}`, requireAuth, async (req, res, next) => { try { res.status(201).json(await Model.create(cleanPayload(req.body))); } catch (error) { error.status = 400; next(error); } });
  app.get(`/api/${type}`, requireAuth, async (_, res, next) => { try { res.json(await Model.find().sort({ createdAt: -1 })); } catch (error) { next(error); } });
  app.get(`/api/${type}/:id`, requireAuth, async (req, res, next) => { try { const data = await Model.findById(req.params.id); if (!data) return res.status(404).json({ message: 'Record not found' }); res.json(data); } catch (error) { next(error); } });
  app.put(`/api/${type}/:id`, requireAuth, async (req, res, next) => { try { const data = await Model.findByIdAndUpdate(req.params.id, cleanPayload(req.body), { new: true, runValidators: true }); if (!data) return res.status(404).json({ message: 'Record not found' }); res.json(data); } catch (error) { error.status = 400; next(error); } });
  app.delete(`/api/${type}/:id`, requireAuth, async (req, res, next) => { try { const data = await Model.findById(req.params.id); if (!data) return res.status(404).json({ message: 'Record not found' }); await DeletedRecord.create({ originalId: data._id, recordType: type, record: data.toObject(), deletedBy: { id: req.user._id, fullName: req.user.fullName, username: req.user.username } }); await data.deleteOne(); res.status(204).end(); } catch (error) { next(error); } });
};
Object.keys(models).forEach(addRegistrationRoutes);
app.patch('/api/:type/:id/payment', requireAuth, async (req, res, next) => { try { const Model = models[req.params.type]; if (!Model) return res.status(404).json({ message: 'Registration type not found' }); const data = await Model.findByIdAndUpdate(req.params.id, { paid: Boolean(req.body.paid) }, { new: true, runValidators: true }); if (!data) return res.status(404).json({ message: 'Record not found' }); res.json(data); } catch (error) { next(error); } });
app.get('/api/overview', requireAuth, async (_, res, next) => { try { const grouped = await Promise.all(Object.entries(models).map(async ([type, Model]) => { const [summary] = await Model.aggregate([{ $group: { _id: null, count: { $sum: 1 }, money: { $sum: '$moneyAmount' }, paid: { $sum: { $cond: ['$paid', '$moneyAmount', 0] } } } }]); return { type, count: summary?.count || 0, money: summary?.money || 0, paid: summary?.paid || 0 }; })); const totals = grouped.reduce((result, item) => ({ count: result.count + item.count, money: result.money + item.money, paid: result.paid + item.paid }), { count: 0, money: 0, paid: 0 }); res.json({ byType: grouped, total: totals.count, totalMoney: totals.money, totalPaid: totals.paid, totalUnpaid: totals.money - totals.paid }); } catch (error) { next(error); } });
app.get('/api/users', requireAuth, requireBranch('hargeisa'), async (_, res, next) => { try { res.json(await User.find().select('-passwordHash').sort({ createdAt: -1 })); } catch (error) { next(error); } });
app.put('/api/users/:id', requireAuth, requireBranch('hargeisa'), async (req, res, next) => { try { const data = await User.findByIdAndUpdate(req.params.id, { fullName: String(req.body.fullName || '').trim(), username: String(req.body.username || '').trim().toLowerCase() }, { new: true, runValidators: true }).select('-passwordHash'); if (!data) return res.status(404).json({ message: 'User not found' }); res.json(data); } catch (error) { error.status = error.code === 11000 ? 409 : 400; error.message = error.code === 11000 ? 'That username is already in use.' : error.message; next(error); } });
app.patch('/api/users/:id/password', requireAuth, requireBranch('hargeisa'), async (req, res, next) => { try { if (!req.body.password || req.body.password !== req.body.confirmPassword) return res.status(400).json({ message: 'Passwords must match.' }); const data = await User.findByIdAndUpdate(req.params.id, { passwordHash: await bcrypt.hash(String(req.body.password), 12) }, { new: true }).select('-passwordHash'); if (!data) return res.status(404).json({ message: 'User not found' }); res.json(data); } catch (error) { next(error); } });
app.delete('/api/users/:id', requireAuth, requireBranch('hargeisa'), async (req, res, next) => { try { if (req.params.id === req.user._id.toString()) return res.status(400).json({ message: 'You cannot delete your own account.' }); const data = await User.findById(req.params.id); if (!data) return res.status(404).json({ message: 'User not found' }); await DeletedRecord.create({ originalId: data._id, recordType: 'user', record: data.toObject(), deletedBy: { id: req.user._id, fullName: req.user.fullName, username: req.user.username } }); await data.deleteOne(); res.status(204).end(); } catch (error) { next(error); } });
app.get('/api/recycle-bin', requireAuth, async (_, res, next) => { try { res.json((await DeletedRecord.find().sort({ deletedAt: -1 })).map(publicDeleted)); } catch (error) { next(error); } });
app.get('/api/recycle-bin/:id', requireAuth, async (req, res, next) => { try { const record = await DeletedRecord.findById(req.params.id); if (!record) return res.status(404).json({ message: 'Deleted record not found' }); res.json(publicDeleted(record)); } catch (error) { next(error); } });
app.post('/api/recycle-bin/:id/restore', requireAuth, requireBranch('hargeisa'), async (req, res, next) => { try { const deleted = await DeletedRecord.findById(req.params.id); if (!deleted) return res.status(404).json({ message: 'Deleted record not found' }); if (deleted.recordType === 'user') { const restoredUser = await User.create({ ...deleted.record, _id: deleted.originalId }); await deleted.deleteOne(); return res.json(publicUser(restoredUser)); } const Model = models[deleted.recordType]; const { _id, __v, ...record } = deleted.record; const restored = await Model.create({ ...record, _id: deleted.originalId }); await deleted.deleteOne(); res.json(restored); } catch (error) { error.status = 400; next(error); } });
app.delete('/api/recycle-bin/:id', requireAuth, async (req, res, next) => { try { const deleted = await DeletedRecord.findByIdAndDelete(req.params.id); if (!deleted) return res.status(404).json({ message: 'Deleted record not found' }); res.status(204).end(); } catch (error) { next(error); } });

app.get('/api/manager/profile', requireAuth, async (req, res, next) => { try { if (!req.user.profileImage) return res.status(404).end(); res.sendFile(req.user.profileImage); } catch (error) { next(error); } });
app.put('/api/manager/profile', requireAuth, upload.single('profile'), async (req, res, next) => { try { if (!req.file) return res.status(400).json({ message: 'A valid image is required' }); await User.findByIdAndUpdate(req.user._id, { profileImage: req.file.path }); res.json({ message: 'Profile image updated.' }); } catch (error) { next(error); } });
app.patch('/api/manager/account', requireAuth, async (req, res, next) => { try { const fullName = String(req.body.fullName || '').trim(); const username = String(req.body.username || '').trim().toLowerCase(); if (!fullName || username.length < 3) return res.status(400).json({ message: 'Full name and a valid username are required.' }); const user = await User.findByIdAndUpdate(req.user._id, { fullName, username }, { new: true, runValidators: true }).select('-passwordHash'); res.json(publicUser(user)); } catch (error) { error.status = error.code === 11000 ? 409 : 400; error.message = error.code === 11000 ? 'That username is already in use.' : error.message; next(error); } });
app.get('/api/manager/logo', requireAuth, requireBranch('hargeisa'), async (req, res, next) => { try { if (!req.user.logoImage) return res.status(404).end(); res.sendFile(req.user.logoImage); } catch (error) { next(error); } });
app.put('/api/manager/logo', requireAuth, requireBranch('hargeisa'), upload.single('logo'), async (req, res, next) => { try { if (!req.file) return res.status(400).json({ message: 'A valid image is required' }); await User.findByIdAndUpdate(req.user._id, { logoImage: req.file.path }); res.json({ message: 'Dashboard logo updated.' }); } catch (error) { next(error); } });
app.get('/api/health', (_, res) => res.json({ status: 'ok', database: mongoose.connection.readyState === 1 ? 'connected' : 'disconnected' }));
app.use((error, _, res, __) => res.status(error.status || 500).json({ message: error.name === 'ValidationError' ? 'Please complete all required fields.' : error.message || 'Server error' }));

async function seedManagers() { const defaults = [{ fullName: 'Yasiin Mohamed', username: process.env.HARGEISA_USERNAME || 'yasiin', password: process.env.HARGEISA_PASSWORD || 'yasiin123', branch: 'hargeisa' }, { fullName: 'Jidda Manager', username: process.env.JIDDA_USERNAME || 'jidda', password: process.env.JIDDA_PASSWORD || 'jidda123', branch: 'jidda' }]; for (const manager of defaults) { if (!(await User.exists({ username: manager.username }))) await User.create({ ...manager, passwordHash: await bcrypt.hash(manager.password, 12) }); } }
mongoose.connect(process.env.MONGODB_URI).then(async () => { await seedManagers(); app.listen(PORT, () => console.log(`Cabiir API running on ${PORT}`)); }).catch(error => { console.error('MongoDB connection failed:', error.message); process.exit(1); });
